version: 0.2

phases:
  install:
    commands:
      - pyenv install -s 3.7.17
      - pyenv global 3.7.17
      - pip install aws-sam-cli
      - sam --version # Check if SAM CLI is installed correctly

      - echo Installing Python 3.9
      - sudo apt-get update -y
      - sudo apt-get install python3.9 -y
      - python3.9 --version # Confirm the correct version is installed

      # Install pip for Python 3.9
      - curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      - python3.9 get-pip.py
      - python3.9 -m pip --version # Verify pip installation for Python 3.9

  build:
    commands:
      - python3.9 -m pip install -r requirements.txt # Ensure dependencies are installed
      - sam build
      - sam deploy --no-fail-on-empty-changeset
      - cd front-end-react
      - npm install
      - npm run build
      - aws s3 sync --acl public-read build s3://emr123-trivia-app-bucket/
